
(function(){
"use strict";
var D=window.FANCY_FIVE_DICTIONARY||new Set(), P=window.FANCY_FIVE_PUZZLES||[];
var $=function(id){return document.getElementById(id)}, STORAGE="wffFancyFiveLaunchV1";
function dateKey(d){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
var today=dateKey(new Date()), puzzle=P.find(function(x){return x.date===today}) || P.filter(function(x){return x.date<=today}).slice(-1)[0] || P[0];
if(!puzzle){$("ff-message").textContent="No puzzle is scheduled.";return}
var answer=puzzle.word.toUpperCase(), guesses=[], finished=false, resultWin=false;
var store={days:{},stats:{played:0,wins:0,currentStreak:0,maxStreak:0,lastWinDate:null}};
try{store=JSON.parse(localStorage.getItem(STORAGE))||store}catch(e){}
store.days=store.days||{};store.stats=Object.assign({played:0,wins:0,currentStreak:0,maxStreak:0,lastWinDate:null},store.stats||{});
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(store))}catch(e){}}
function emit(name,params){try{window.dataLayer=window.dataLayer||[];window.dataLayer.push(Object.assign({event:name,puzzle_date:today},params||{}))}catch(e){}}
function dayDiff(a,b){if(!a||!b)return null;var aa=new Date(a+"T12:00:00"),bb=new Date(b+"T12:00:00");return Math.round((bb-aa)/86400000)}
function score(g){var out=["ff-absent","ff-absent","ff-absent","ff-absent","ff-absent"],cnt={},i,c;for(i=0;i<5;i++){if(g[i]===answer[i])out[i]="ff-correct";else{c=answer[i];cnt[c]=(cnt[c]||0)+1}}for(i=0;i<5;i++){if(out[i]==="ff-correct")continue;c=g[i];if((cnt[c]||0)>0){out[i]="ff-present";cnt[c]--}}return out}
function board(){var b=$("ff-board");b.innerHTML="";for(var r=0;r<6;r++){var sc=guesses[r]?score(guesses[r]):null;for(var c=0;c<5;c++){var t=document.createElement("div");t.className="ff-tile";t.setAttribute("aria-label","row "+(r+1)+" column "+(c+1));if(guesses[r]){t.textContent=guesses[r][c];t.classList.add(sc[c])}b.appendChild(t)}}}
function keys(){var pr={"ff-absent":1,"ff-present":2,"ff-correct":3},st={};guesses.forEach(function(g){score(g).forEach(function(s,i){var c=g[i];if(!st[c]||pr[s]>pr[st[c]])st[c]=s})});var k=$("ff-keyboard");k.innerHTML="";["QWERTYUIOP","ASDFGHJKL","ZXCVBNM"].forEach(function(chars){var row=document.createElement("div");row.className="ff-keyrow";chars.split("").forEach(function(letter){var b=document.createElement("button");b.type="button";b.className="ff-button ff-key";b.textContent=letter;b.setAttribute("aria-label","Letter "+letter);if(st[letter])b.classList.add(st[letter]);b.onclick=function(){var inp=$("ff-guess");if(!finished&&inp.value.length<5){inp.value=(inp.value+letter).toUpperCase();inp.focus()}};row.appendChild(b)});k.appendChild(row)})}
function stats(){var s=store.stats;$("ff-played").textContent=s.played;$("ff-winrate").textContent=(s.played?Math.round(s.wins/s.played*100):0)+"%";$("ff-streak").textContent=s.currentStreak;$("ff-maxstreak").textContent=s.maxStreak}
function showResult(win,fromLoad){finished=true;resultWin=win;$("ff-guess").disabled=true;$("ff-enter").disabled=true;$("ff-result-title").textContent=win?"You found it.":"Come back for tomorrow's First.";$("ff-answer").textContent="TODAY'S WORD: "+answer;$("ff-fact").textContent=puzzle.fact;$("ff-result").hidden=false;stats();if(!fromLoad)emit("fancy_five_complete",{won:win,guesses:guesses.length})}
function complete(win){if(!store.days[today]||!store.days[today].completed){store.stats.played++;if(win){store.stats.wins++;var gap=dayDiff(store.stats.lastWinDate,today);store.stats.currentStreak=(gap===1)?store.stats.currentStreak+1:1;store.stats.lastWinDate=today;store.stats.maxStreak=Math.max(store.stats.maxStreak,store.stats.currentStreak)}else store.stats.currentStreak=0}store.days[today]={guesses:guesses.slice(),completed:true,won:win};save();$("ff-message").textContent=win?"You found today's First in "+guesses.length+"!":"Today's word was "+answer+".";showResult(win,false)}
function submit(){if(finished)return;var inp=$("ff-guess"),g=inp.value.toUpperCase().replace(/[^A-Z]/g,"").slice(0,5);if(g.length!==5){$("ff-message").textContent="Please enter exactly five letters.";return}if(g!==answer&&!D.has(g)){$("ff-message").textContent="Not a recognized English word. Try again.";return}guesses.push(g);inp.value="";board();keys();emit("fancy_five_guess",{guess_number:guesses.length});store.days[today]={guesses:guesses.slice(),completed:false,won:false};save();if(g===answer)complete(true);else if(guesses.length>=6)complete(false);else $("ff-message").textContent=(6-guesses.length)+" "+((6-guesses.length)===1?"try":"tries")+" remaining."}
function shareText(){var grid=guesses.map(function(g){return score(g).map(function(s){return s==="ff-correct"?"🟩":s==="ff-present"?"🟨":"⬜"}).join("")}).join("\n");return "Winter FancyFaire* Fancy Five "+guesses.length+"/6\n\n"+grid+"\n\nWhere Firsts Are Found"}
function share(){var txt=shareText();if(navigator.share){navigator.share({title:"Winter FancyFaire* Fancy Five",text:txt}).catch(function(){})}else if(navigator.clipboard){navigator.clipboard.writeText(txt).then(function(){$("ff-message").textContent="Results copied!"}).catch(function(){$("ff-message").textContent="Copy your results from the share panel."})}emit("fancy_five_share",{won:resultWin})}
$("ff-category").textContent=puzzle.category;$("ff-form").onsubmit=function(e){e.preventDefault();submit()};$("ff-enter").onclick=submit;$("ff-guess").oninput=function(){this.value=this.value.toUpperCase().replace(/[^A-Z]/g,"").slice(0,5)};$("ff-guess").onkeydown=function(e){if(e.key==="Enter"){e.preventDefault();submit()}};$("ff-share").onclick=share;
$("ff-backspace").onclick=function(){var i=$("ff-guess");i.value=i.value.slice(0,-1);i.focus()};$("ff-clear").onclick=function(){$("ff-guess").value="";$("ff-guess").focus()};
var modal=$("ff-modal");$("ff-help").onclick=function(){modal.hidden=false;$("ff-close").focus()};$("ff-close").onclick=function(){modal.hidden=true;$("ff-help").focus()};modal.onclick=function(e){if(e.target===modal)modal.hidden=true};document.addEventListener("keydown",function(e){if(e.key==="Escape")modal.hidden=true});
var existing=store.days[today];if(existing){guesses=(existing.guesses||[]).slice(0,6);board();keys();if(existing.completed){$("ff-message").textContent=existing.won?"You already found today's First!":"Today's word was "+answer+".";showResult(!!existing.won,true)}}
board();keys();stats();if(!existing)emit("fancy_five_start",{});if(!finished)$("ff-guess").focus();
})();
